version: '3.9'

services:
  user_service:
    build: user_service
    volumes:
      - ./user_service:/app
    
    ports:
      - "8080:8000"
    
    env_file:
      .env
    
    depends_on:
      - users_db
  
  
  users_db:
    image: postgres:15
    env_file:
      - .env
    restart: always
    ports:
      - "5454:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data


  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq


  gateway_service:
    build: ./gateway_service
    volumes:
      - ./gateway_service:/app
    ports:
      - "8081:4444"
    
    env_file:
      - ./gateway_service/.env

    depends_on:
      - rabbitmq
      - user_service
      - convert_service


  convert_service:
    build: ./convert_service
    volumes:
      - ./convert_service:/app
      - media_uploads:/app/media_uploads

    env_file:
      - ./convert_service/.env
    
    depends_on:
      - rabbitmq
    

  media_service:
    build: ./media_service
    
    depends_on:
      - rabbitmq
    
    volumes:
      - ./media_service:/app
      - media_uploads:/app/media_uploads
    
    ports:
      - "8082:8000"
    
    env_file:
      - .env



volumes:
  users_db_data:
  rabbitmq:
  media_uploads:
